#**Pytorch Tensor Basic Usage**<br>

*   create Tensor
*   Indexing, Joining, Slicing
*   Initializatiion
*   Math Operations


새 노트에서 런타임 > 런타임 유형 변경 > GPU 지정 <br>
새 노트마다 다시 지정해야 함

In [9]:
# 1. Create Tensor
# 1) random numbers
import torch

# torch.rand(sizes) => 0 ~ 1 사이의 값으로 랜덤값 발생함
# sizes : 1차원 갯수 | 2차원 행렬 갯수 지정
# 0과 1사이의 실수형 숫자를 균등하게 생성
x = torch.rand(2,3) # 2행 3열로 탠서를  생성하고, 랜덤값으로 채움

x
print(x)

tensor([[0.9924, 0.8886, 0.3122],
        [0.3997, 0.6930, 0.0852]])


In [10]:
# 2. torch.randn(sizes)
# 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해서 랜덤값 생성
x = torch.randn(2, 3)
x

tensor([[-0.4870, -0.4877,  1.0129],
        [ 0.6604, -0.4177, -0.0091]])

In [11]:
# 3. torch.randperm(n) => permutation of 0~ n
x = torch.randperm(5)
x

tensor([2, 4, 0, 1, 3])

랜덤값을 가지는 텐서 생성 함수들 <br>
1. torch.rand()         :  0 과 1 사이의 숫자를 균등하게 생성<br>
2. torch.rand_like()    : 사이즈를 튜플로 입력하지 않고 기존의 텐서와 동일한 텐서 만들 때 사용<br>
3. torch.randn()        : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 생성<br>
4. torch.rand_like()    : 사이즈를 튜플로 입력하지 않고 기존의 텐서를 정의함<br>
5. torch.randint()      : 주어진 범위 내의 정수를 균등하게 생성, 자료형은 torch.float32 <br>
6. torch.randint_like() : 기존의 텐서를 정의함<br>
7. torch.randperm()     : 주어진 범위 내의 정수를 랜덤하게 생성 <br>


In [12]:
# 2) zeros, ones, arange

# torch.zeros(2, 3) => [[0,0,0],[0,0,0]]
x = torch.zeros(2,3)
x # float32

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
# torch.ones(2, 3)
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
# torch.arange(start, end, step)
x = torch.arange(0, 3, step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

# 3. Tensor Data Type


In [15]:
# torch.floatTensor(size or list)
x = torch.FloatTensor(2, 3)
x

tensor([[-1.4018e-03,  4.5111e-41, -1.4018e-03],
        [ 4.5111e-41,  4.4842e-44,  0.0000e+00]])

In [16]:
x = torch.FloatTensor([12, 35])
x

tensor([12., 35.])

In [17]:
# torch.type_as(tensor_type)
# 기존의 텐서의 값의 자료형을 바꿀 때 사용
x = x.type_as(torch.IntTensor())
x

tensor([12, 35], dtype=torch.int32)

# 4. Numpy to Tensor, Tensor to Numpy

In [18]:
import numpy as np

# torch.from_numpy(ndarray) => tensor
x1 = np.ndarray(shape=(2, 3), dtype = int, buffer=np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)
x2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
# torch.numpy() -> ndarray
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

# 5. Tensor on CPU & GPU


In [20]:
x = torch.FloatTensor(([1, 2, 3], [4, 5, 6]))
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [21]:
x_gpu = x.cuda()
x_gpu

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [22]:
x_cpu = x_gpu.cpu()
x_cpu

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# 6. Tensor Size

In [28]:
# tensor.size() => 인덱스 값
x = torch.FloatTensor(10, 12, 3, 3)
x.size()[:]
print(x, x.size()[:])

tensor([[[[2.8026e-45, 5.6052e-45, 1.2612e-44],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [1.4854e-43, 4.2039e-45, 2.8026e-45]],

         [[2.8026e-45, 5.6052e-45, 2.9427e-44],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [1.4013e-43, 0.0000e+00, 2.8026e-45]],

         [[2.8026e-45, 3.0829e-44, 3.3631e-44],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [1.4013e-43, 1.4013e-45, 2.8026e-45]],

         ...,

         [[       nan,        nan,        nan],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [

# 2. Indexing, Slicing, Joining
#1) Indexing

In [33]:
# torch.index_select(input, dim, index)
# input : 대상 텐서
# dim : 선택할 차원의 인덱스를 지정, 0은 첫번째 차원(행을 의미), 1은 두번째 차원(열을 의미)을 의미함
# index : 선택할 인덱스를 포함한 1차원 텐서를 정의함, [0,3]은 0번째와 3번째를 의미함
x = torch.rand(4, 3)
out = torch.index_select(x, 0, torch.LongTensor([0, 3])) # x 텐서에서 0행과 3행 추출
print( x, '\n', out )

tensor([[0.0674, 0.8718, 0.5319],
        [0.7610, 0.4346, 0.1439],
        [0.6445, 0.2820, 0.4269],
        [0.1746, 0.4917, 0.1268]]) 
 tensor([[0.0674, 0.8718, 0.5319],
        [0.1746, 0.4917, 0.1268]])


In [ ]:
# 파이썬 indexing 사용 가능
x[:, 0], x[0, :], x[0:2, 0:2]

In [36]:
# torch.masked_select(input, mask)
x = torch.randn(2,3)
mask = torch.BoolTensor([[False, False, True], [False, True, False]])
out= torch.masked_select(x, mask)
x, mask, out

(tensor([[-1.7289,  0.7191,  0.8838],
         [ 2.0662, -0.9881,  2.7275]]),
 tensor([[False, False,  True],
         [False,  True, False]]),
 tensor([ 0.8838, -0.9881]))

# 2) Joining

In [38]:
# torch.cat(seq, dim=0)
x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])

z1 = torch.cat([x,y], dim=0) # dim=0 (행방향) : 아래로 합침
z2 = torch.cat([x,y], dim=1) # dim=1 (열방향) : 오른쪽에 합쳐짐

x, y, z1, z2


(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [39]:
# torch.stack(sequences, dim=0) => 새로운 차원으로 추가
x = torch.FloatTensor([[1,2,3],[4,5,6]]) # shape : (2, 3)
x_stack = torch.stack([x,x,x,x], dim=0) # shape : (4, 2, 3)
x_stack



tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

# 3) Slicing

In [40]:
# torch.chunk(tensor, chunks, dim=0)
x_1, x_2 = torch.chunk(z1, 2, dim=0) # dim=0 : 행들을 2개로 분할
y_1, y_2, y_3 = torch.chunk(z1, 3 , dim=1) # dim=1 : 열들을 3개로 분할

z1, x_1, x_2, y_1, y_2, y_3

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.],
         [ 4.],
         [-1.],
         [-4.]]),
 tensor([[ 2.],
         [ 5.],
         [-2.],
         [-5.]]),
 tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

In [41]:
# torch.split(tensor, split_size, dim=0)
x1, x2 = torch.split(z1, 2, dim=0) # 행으로 2개 분리
y1 = torch.split(z1, 2, dim=1) # 3개의 열을 2개로 분리

z1, x1, x2, y1

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 (tensor([[ 1.,  2.],
          [ 4.,  5.],
          [-1., -2.],
          [-4., -5.]]),
  tensor([[ 3.],
          [ 6.],
          [-3.],
          [-6.]])))

# 4) squeezing


In [44]:
# torch.squeeze(input, dim=None) => 숫자가 1 인 차원을 제거
x1 = torch.FloatTensor(10, 1, 3, 4)
# 차원(dimension)의 개념
# 10 : batch size (데이터 한 묶음당 들어있는 데이터(x,y)쌍 갯수)
# 1 : channel size (색상 채널 1은 그레이톤 흑백이미지를 의미함)
# 3 : width image size
# 4 : height image size

x2 = torch.squeeze(x1)

x1, x2, x1.size(), x2.size()

(tensor([[[[-1.4019e-03,  4.5111e-41,  1.1976e-11,  0.0000e+00],
           [ 3.8676e-43,  0.0000e+00,  2.5882e+26, -9.8732e+07],
           [ 4.4816e-38,  0.0000e+00,  0.0000e+00,  1.7927e-37]]],
 
 
         [[[ 0.0000e+00,  0.0000e+00,  9.5709e-43,  0.0000e+00],
           [ 1.1401e-38,  1.5835e-42,  0.0000e+00,  0.0000e+00],
           [ 0.0000e+00,  0.0000e+00,  2.6597e-42,  0.0000e+00]]],
 
 
         [[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  3.3911e-42],
           [ 0.0000e+00,  4.6285e-38,  5.9835e-43,  0.0000e+00],
           [ 5.9835e-43,  0.0000e+00,  4.4816e-38,  0.0000e+00]]],
 
 
         [[[ 0.0000e+00,  1.1748e-32,  0.0000e+00,  0.0000e+00],
           [ 9.5709e-43,  0.0000e+00,  1.1401e-38,  1.5835e-42],
           [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]],
 
 
         [[[ 2.6597e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00],
           [ 0.0000e+00,  4.8261e-42,  0.0000e+00,  4.6285e-38],
           [ 5.9835e-43,  0.0000e+00,  5.9835e-43,  0.0000e+00]]],

In [46]:
# torch.unsqueeze(input, dim=None) => 숫자가 1인 차원을 추가
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.unsqueeze(x1, dim=0) # dim=0 면 첫번째 도메인 위치에 추가

x1, x2, x1.size(), x2.size()

(tensor([[[3.2314e-18, 3.4034e-18, 7.0976e+22, 4.3605e+27],
          [1.5766e-19, 1.7743e+28, 3.2856e-18, 7.4767e+20],
          [1.6534e+19, 1.7860e+31, 1.5766e-19, 1.1434e+27]],
 
         [[1.2845e+31, 1.8062e+28, 7.1297e+28, 6.1961e-04],
          [6.2611e+22, 4.7428e+30, 7.3988e+31, 4.5925e+24],
          [1.9434e-19, 4.4721e+21, 1.5956e+25, 4.7399e+16]],
 
         [[2.3308e-09, 3.7293e-08, 8.1121e+17, 1.4580e-19],
          [4.3605e+27, 2.7722e+20, 6.1949e-04, 1.5562e+28],
          [2.7946e+20, 1.1838e+33, 1.4580e-19, 1.7751e+28]],
 
         [[3.1503e-18, 3.0186e+32, 1.4605e-19, 1.1286e+27],
          [1.5766e-19, 1.1434e+27, 1.1963e+22, 1.8058e+28],
          [7.2251e+28, 1.5766e-19, 1.1434e+27, 1.1963e+22]],
 
         [[7.7133e+31, 1.1259e+24, 2.1715e-18, 2.0281e-19],
          [1.8019e+31, 1.8062e+28, 2.3056e-12, 7.5246e+28],
          [6.7131e+22, 1.2397e+28, 3.3598e-12, 1.8038e+28]],
 
         [[1.6488e+22, 1.8058e+28, 7.2251e+28, 1.5766e-19],
          [1.1434e+27, 2.

# 3. Initialization

In [59]:
import torch.nn.init as init

x1 = init.uniform(torch.FloatTensor(3, 4), a=0, b=9) # a와 b 사이의 값으로 초기화
x2 = init.normal(torch.FloatTensor(3, 4), std=0.2) # 표준편차 0.2를 적용해서 초기화
x3 = init.constant(torch.FloatTensor(3, 4), 3.1415926535) # 지정된 상수값으로 초기화

x1, x2, x3




/tmp/ipykernel_1967/3185247120.py:3: FutureWarning: `nn.init.uniform` is now deprecated in favor of `nn.init.uniform_`.
  x1 = init.uniform(torch.FloatTensor(3, 4), a=0, b=9) # a와 b 사이의 값으로 초기화
/tmp/ipykernel_1967/3185247120.py:4: FutureWarning: `nn.init.normal` is now deprecated in favor of `nn.init.normal_`.
  x2 = init.normal(torch.FloatTensor(3, 4), std=0.2) # 표준편차 0.2를 적용해서 초기화
/tmp/ipykernel_1967/3185247120.py:5: FutureWarning: `nn.init.constant` is now deprecated in favor of `nn.init.constant_`.
  x3 = init.constant(torch.FloatTensor(3, 4), 3.1415926535) # 지정된 상수값으로 초기화


(tensor([[4.6670, 8.4650, 7.2446, 8.9448],
         [2.5298, 8.6972, 4.6439, 3.8506],
         [0.0735, 7.1486, 3.0071, 4.9429]]),
 tensor([[ 0.0897,  0.1579,  0.4651,  0.2093],
         [ 0.0507, -0.0663,  0.2618, -0.2007],
         [ 0.2172, -0.0484, -0.0302,  0.2965]]),
 tensor([[3.1416, 3.1416, 3.1416, 3.1416],
         [3.1416, 3.1416, 3.1416, 3.1416],
         [3.1416, 3.1416, 3.1416, 3.1416]]))

# 4. Math Operation
# 1. Arithmetic Operations

In [61]:
# torch.add() : 더하기 (백터연산 개념)
x1 = torch.FloatTensor([[1,2,3], [4,5,6]])
x2 = torch.FloatTensor([[1,2,3], [4,5,6]])
add = torch.add(x1, x2)

x1, x2, add, x1+x2, x1-x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [62]:
# torch.add() broadcasting (숫자와의 연산)
x2 = torch.add(x1, 10)

x1, x2, x1 + 10, x2 - 10


(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [63]:
# torch.mul() : 곱하기
x1 = torch.FloatTensor([[1,2,3], [4,5,6]])
x2 = torch.FloatTensor([[1,2,3], [4,5,6]])
mul = torch.mul(x1, x2)

x1, x2, mul, x1*x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]))

In [67]:
# torch.mul() broadcasting (숫자와의 연산)
mul2 = torch.mul(x1, 10)
mul2, x1 * 10, mul2 == x1*10

(tensor([[10., 20., 30.],
         [40., 50., 60.]]),
 tensor([[10., 20., 30.],
         [40., 50., 60.]]),
 tensor([[True, True, True],
         [True, True, True]]))

In [69]:
# torch.div() : 나누기 (몫)
div = torch.div(x1, 5)

div, x1 / 5, div == x1/5

(tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]),
 tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]),
 tensor([[True, True, True],
         [True, True, True]]))

# 2) Other Math Operations

In [70]:
# torch.pow(input, exponent)
x1 = torch.FloatTensor(3, 4)

x1, torch.pow(x1, 2), x1 ** 2

(tensor([[3.3867e-12, 0.0000e+00, 5.2044e+00, 4.3811e+00],
         [8.3335e+00, 4.9153e+00, 2.3925e+00, 8.3793e+00],
         [4.3725e-01, 7.1239e+00, 1.4371e+00, 7.7367e+00]]),
 tensor([[1.1470e-23, 0.0000e+00, 2.7086e+01, 1.9194e+01],
         [6.9448e+01, 2.4160e+01, 5.7241e+00, 7.0212e+01],
         [1.9118e-01, 5.0750e+01, 2.0653e+00, 5.9857e+01]]),
 tensor([[1.1470e-23, 0.0000e+00, 2.7086e+01, 1.9194e+01],
         [6.9448e+01, 2.4160e+01, 5.7241e+00, 7.0212e+01],
         [1.9118e-01, 5.0750e+01, 2.0653e+00, 5.9857e+01]]))

In [73]:
# torch.exp(tensor, out=None) : 지수함수
x1 = torch.FloatTensor(3, 4)
out = torch.exp(x1)

x1, out

(tensor([[6.2366e-12, 0.0000e+00, 6.3411e-02, 2.3665e-01],
         [1.1254e-01, 4.5486e-01, 2.1328e-01, 3.8620e-01],
         [4.9656e-01, 5.3842e-02, 1.4792e-01, 1.8950e-02]]),
 tensor([[1.0000, 1.0000, 1.0655, 1.2670],
         [1.1191, 1.5760, 1.2377, 1.4714],
         [1.6431, 1.0553, 1.1594, 1.0191]]))

In [74]:
# torch.log(input, *, out=None)
out = torch.log(x1)

x1, out

(tensor([[6.2366e-12, 0.0000e+00, 6.3411e-02, 2.3665e-01],
         [1.1254e-01, 4.5486e-01, 2.1328e-01, 3.8620e-01],
         [4.9656e-01, 5.3842e-02, 1.4792e-01, 1.8950e-02]]),
 tensor([[-25.8006,     -inf,  -2.7581,  -1.4412],
         [ -2.1844,  -0.7878,  -1.5451,  -0.9514],
         [ -0.7000,  -2.9217,  -1.9111,  -3.9660]]))

# 3) Matrix Operations

In [76]:
# torch.mm(mat1, mat2) => matrix multiplication (행렬곱)
x1 = torch.FloatTensor(3, 4)
x2 = torch.FloatTensor(4, 5)
out = torch.mm(x1, x2)

x1, x2, out


(tensor([[-1.4018e-03,  4.5111e-41,  2.1869e-11,  0.0000e+00],
         [-1.6583e-01, -4.7712e-02, -2.8920e-01, -7.3089e-02],
         [-5.8709e-02,  1.7767e-01,  5.1661e-01,  2.9297e-01]]),
 tensor([[-1.4018e-03,  4.5111e-41,  6.9515e-12,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]),
 tensor([[ 1.9651e-06, -6.3058e-44, -9.7448e-15,  0.0000e+00,  0.0000e+00],
         [ 2.3247e-04, -7.4801e-42, -1.1528e-12,  0.0000e+00,  0.0000e+00],
         [ 8.2300e-05, -2.6485e-42, -4.0812e-13,  0.0000e+00,  0.0000e+00]]))

In [77]:
# torch.bmm(batch1, batch2) => batch에 대한 행렬곱 연산
# 맨 앞의 batch 는 차원을 유지하면서 뒤 요소들의 행렬곱 연산 수행함

x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.FloatTensor(10, 4, 5)
out = torch.bmm(x1, x2)

out.size()


torch.Size([10, 3, 5])

In [78]:
# torch.dot(tensor1, tensor2)
x1 = torch.FloatTensor([1,2,3,4])
x2 = torch.FloatTensor([2,3,4,5])

torch.dot(x1, x2)
# 2+3+4+5 + 4+6+8+10 + 6+9+12+15 + 8+12+16+20

tensor(40.)

In [79]:
# torch.t(matrix) : 텐서의 전치 연산 (행과열을 바꾸는 연산)
x1 = torch.FloatTensor(3, 4)

x1, x1.t(), torch.t(x1)

(tensor([[2.8786e-11, 0.0000e+00, 3.1416e+00, 3.1416e+00],
         [3.1416e+00, 3.1416e+00, 3.1416e+00, 3.1416e+00],
         [3.1416e+00, 3.1416e+00, 3.1416e+00, 3.1416e+00]]),
 tensor([[2.8786e-11, 3.1416e+00, 3.1416e+00],
         [0.0000e+00, 3.1416e+00, 3.1416e+00],
         [3.1416e+00, 3.1416e+00, 3.1416e+00],
         [3.1416e+00, 3.1416e+00, 3.1416e+00]]),
 tensor([[2.8786e-11, 3.1416e+00, 3.1416e+00],
         [0.0000e+00, 3.1416e+00, 3.1416e+00],
         [3.1416e+00, 3.1416e+00, 3.1416e+00],
         [3.1416e+00, 3.1416e+00, 3.1416e+00]]))

In [80]:
# torch.transpose(input, dim_0, dim_1)
# 바꿀 차원을 2개 지정함 => 텐서 내부 차원끼리 바꾸기함
x1 = torch.FloatTensor(10, 3, 4)

# 1차원과 2차원을 서로 바꿈
x1.size(), torch.transpose(x1, 1, 2).size(), x1.transpose(1, 2).size()


(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [83]:
# torch.eig(input, eigenvectors=False)
# 고유값 (eigen_value), 고유백터(eigen_vector) 로 변환하는 함수
x1 = torch.FloatTensor(4, 4)

# 고유값과 고유백터 계산
x1, torch.linalg.eig(x1)
# 고유값과 고유백터 :
# 어떤 변환(행렬)을 적용했을 때 방향은 변하지 않고 크기만 변하는 특별한 백터와 변화량을 의미함

# 백터(Vector) : 크기 + 방향을 가진 값임
# 예 : (2, 3) 백터는 오른쪽 2, 위쪽 3 방향을 가짐

# 행렬(Matrix) : 백터를 변형시키는 도구
# 예 : 회전, 확대, 축소, 뒤집기 등을 수행
# 예 : [1,0] => [2,0] 크기가 2배 => 고유값은 2임 (고유백터가 얼마나 확대/축소되었는지 나타내는 값)


(tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31],
         [7.2708e+31, 5.0778e+31, 3.2608e-12, 1.7728e+28],
         [7.0367e+22, 2.1715e-18, 5.2304e+22, 1.0513e-05],
         [2.7627e-06, 1.6780e-07, 4.1341e-05, 1.2802e-11]]),
 torch.return_types.linalg_eig(
 eigenvalues=tensor([ 5.0778e+31+0.j, -3.5331e+25+0.j,  3.5283e+25+0.j, -4.0474e-02+0.j]),
 eigenvectors=tensor([[ 1.3940e-09+0.j,  5.7272e-01+0.j,  5.7269e-01+0.j,  4.5910e-01+0.j],
         [ 1.0000e+00+0.j, -8.1975e-01+0.j, -8.1977e-01+0.j, -6.4500e-01+0.j],
         [ 1.2122e-17+0.j, -1.1389e-03+0.j,  1.1439e-03+0.j, -6.1090e-01+0.j],
         [ 3.3046e-39+0.j, -3.9555e-32+0.j,  4.2283e-32+0.j,  5.9543e-04+0.j]])))