# Variable & Automatic Gradient Calculation
- Tensor vs Variable
- Graph and Gradient

## 1.Import Required Libraries

In [1]:
import torch
from torch.autograd import Variable

## 2. Tensor vs Variable
### 1) Declaration

In [2]:
x_tensor = torch.Tensor(3, 4)
x_tensor

tensor([[-5.4586e+14,  3.0683e-41,  3.7835e-44,  0.0000e+00],
        [        nan,  6.4460e-44,  1.3733e-14,  6.4069e+02],
        [ 4.3066e+21,  1.1824e+22,  4.3066e+21,  6.3828e+28]])

In [3]:
x_variable = Variable(x_tensor)
x_variable

tensor([[-5.4586e+14,  3.0683e-41,  3.7835e-44,  0.0000e+00],
        [        nan,  6.4460e-44,  1.3733e-14,  6.4069e+02],
        [ 4.3066e+21,  1.1824e+22,  4.3066e+21,  6.3828e+28]])

Variable 은 autogradient 가능함<br>
Pytorch 0.4 이상 버전에서는 Tensor 에 Variable 이 통합되고, Variable 은 deprecated 임. <br>
Tensor 만 사용함

### 2) Variables of a Variable

In [4]:
# data 속성
x_variable.data

tensor([[-5.4586e+14,  3.0683e-41,  3.7835e-44,  0.0000e+00],
        [        nan,  6.4460e-44,  1.3733e-14,  6.4069e+02],
        [ 4.3066e+21,  1.1824e+22,  4.3066e+21,  6.3828e+28]])

In [5]:
# grad 속성 : 값에 대한 gradient
# Variable 생성시 초기화되면서, gradient 도 같이 정의됨
print(x_variable.grad)

None


In [7]:
# requires_grad 속성 : 값에 대한 gradient 요구시 사용
print(x_variable.requires_grad)  # 속성의 설정값 확인 : False
# gradient 가 계산이 안된 상태임

# gradient 에 대한 연산을 모두 추적함 : True
x_variable = Variable(x_tensor, requires_grad=True)
x_variable.requires_grad

False


True

In [9]:
# volatile 속성 : 최소 메모리 사용에 대한 설정
# requires_grad 가 False 이면, volatile 도 자동 False 가 됨

x_variable = Variable(x_tensor, volatile=True)
x_variable.grad, x_variable.requires_grad, x_variable.volatile

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: volatile was removed (Variable.volatile is always False)
  after removing the cwd from sys.path.


(None, False, False)

## 3. Graph & Variables

In [10]:
# create graph

x = Variable(torch.FloatTensor(3, 4), requires_grad=True)
y = x**2 + 4*x
z = 2*y + 3

x.requires_grad, y.requires_grad, z.requires_grad

(True, True, True)

In [11]:
# backward(gradient, retain_graph, create_graph, retain_variables)
# 현재 값 w, r, t, graph 에 대한 gradient 계산 함수임
# 역전파 알고리즘 적용 계산함수

# 위의 z 값으로 x 의 gradient 를 계산해 냄
loss = torch.FloatTensor(3, 4)
z.backward(loss)

print(x.grad)
y.grad, z.grad

tensor([[-4.3670e+15,  2.4546e-40,  1.1547e-42,  1.2780e-42],
        [        nan,  1.1210e-42,  1.1030e-21,  2.8620e-18],
        [ 3.2413e-26,  5.1568e-43,  1.1547e-42,  0.0000e+00]])


/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:1013: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:417.)
  return self._grad


(None, None)